#!/usr/bin/env tsx
/**
 * Regenerate `src/types/enums.ts` from the Blitz OpenAPI spec.
 *
 * The spec pins several request fields to large `enum` lists (most notably
 * `industry`, with hundreds of values). Hand-maintaining those would drift from
 * the API, so this script pulls them straight from the live spec and turns each
 * into:
 *
 *   - a `readonly` `as const` value array (e.g. `INDUSTRY`),
 *   - a string-literal union type (e.g. `Industry`), and
 *   - a Zod schema (e.g. `IndustrySchema = z.enum(INDUSTRY)`).
 *
 * The spec inlines each enum and repeats it across endpoints, request
 * content-types, and `include`/`exclude` sub-objects, so the same value list
 * shows up 6–12 times. We map each enum to a name by its owning request
 * property (`PROPERTY_TO_CLASS`), collapse the identical duplicate occurrences,
 * and de-duplicate exact-repeat values within a list.
 *
 * Three modes:
 *   tsx scripts/gen-enums.ts --fetch    # pull the live spec, rewrite the cache
 *                                       #   (openapi/enum-source.json) AND enums.ts
 *   tsx scripts/gen-enums.ts            # render enums.ts from the committed cache
 *   tsx scripts/gen-enums.ts --check    # exit 1 if enums.ts is out of date
 *
 * Only `--fetch` touches the network. The default render and `--check` read the
 * committed cache offline, so CI's drift guard (`pnpm gen:enums:check`) stays
 * hermetic — it never fails because the network is down or upstream changed.
 *
 * Each value is emitted via `JSON.stringify` so the exact upstream escaping
 * (including the double-backslash apostrophe value) round-trips byte-for-byte.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SOURCE = join(ROOT, "openapi", "enum-source.json");
const TARGET = join(ROOT, "src", "types", "enums.ts");

/** Live OpenAPI spec the enums are pulled from (only `--fetch` reads it). */
const SPEC_URL = "https://api.blitz-api.ai/openapi";

const FETCH_TIMEOUT_MS = 15_000;
const FETCH_ATTEMPTS = 3;

/**
 * Maps a request-body property key to its enum class name. The "owning
 * property" of an enum is the nearest ancestor key that isn't a structural
 * keyword (see `STRUCTURAL`). Declared in the canonical output order so the
 * generated cache — and therefore `enums.ts` — is deterministic regardless of
 * spec traversal order. `type` only ever appears as `company.type`.
 *
 * Two properties may share a class name when the spec repeats one value list
 * under different keys: `size` (`company.size` on `/v2/jobs/search`) carries the
 * same buckets as `employee_range`, so it maps onto `EmployeeRange` rather than
 * emitting a duplicate. Sharing keeps the collapse behaviour above honest — if
 * upstream ever forks the two lists apart, the divergence check throws and names
 * both spec paths, which is exactly the human decision point we want.
 */
const PROPERTY_TO_CLASS: Record<string, string> = {
  industry: "Industry",
  type: "CompanyType",
  employee_range: "EmployeeRange",
  size: "EmployeeRange",
  continent: "Continent",
  sales_region: "SalesRegion",
  job_function: "JobFunction",
  job_level: "JobLevel",
  last_funding_type: "LastFundingType",
  seniority: "Seniority",
  employment_type: "EmploymentType",
  work_arrangement: "WorkArrangement",
};

/** OpenAPI/JSON-Schema keywords skipped when resolving an enum's owning property. */
const STRUCTURAL = new Set([
  "items",
  "include",
  "exclude",
  "properties",
  "schema",
  "content",
  "requestBody",
  "parameters",
  "get",
  "post",
  "put",
  "patch",
  "delete",
  "anyOf",
  "allOf",
  "oneOf",
  "application/json",
  "application/x-www-form-urlencoded",
  "multipart/form-data",
]);

const HEADER = `// This file is @generated by scripts/gen-enums.ts from openapi/enum-source.json.
// Do not edit by hand — run \`pnpm gen:enums\` to regenerate.
//
// Every value is the exact string the Blitz API accepts. Use the string literal
// directly (it autocompletes from the union type) or pass any raw string.
import * as z from "zod";
`;

interface Artifact {
  _comment: string;
  _source_url: string;
  spec_version: string;
  enums: Record<string, string[]>;
}

/** Drop exact-duplicate values, preserving first-seen order. Keeps near-duplicates. */
function dedupeValues(values: string[]): string[] {
  return Array.from(new Set(values));
}

/** The nearest ancestor property key that isn't a structural keyword. */
function owningProperty(path: string[]): string | undefined {
  for (let i = path.length - 1; i >= 0; i--) {
    if (!STRUCTURAL.has(path[i])) return path[i];
  }
  return undefined;
}

/**
 * Walk an OpenAPI spec and collect the mapped enum value lists, keyed by class
 * name in canonical (`PROPERTY_TO_CLASS`) order. Identical duplicate
 * occurrences collapse; divergent ones, or a mapped property missing from the
 * spec, throw (a human should look). Unmapped enums are warned about and skipped.
 */
export function extractEnums(spec: unknown): Record<string, string[]> {
  const found = new Map<string, { values: string[]; path: string }>();
  const seen = new WeakSet<object>();

  function walk(node: unknown, path: string[]): void {
    if (node === null || typeof node !== "object") return;
    if (seen.has(node)) return;
    seen.add(node);

    if (Array.isArray(node)) {
      for (const item of node) walk(item, path);
      return;
    }

    const obj = node as Record<string, unknown>;
    const enumVal = obj.enum;
    if (
      Array.isArray(enumVal) &&
      obj.type === "string" &&
      enumVal.every((v) => typeof v === "string")
    ) {
      const owner = owningProperty(path);
      const jsonPath = path.join(".");
      const className = owner ? PROPERTY_TO_CLASS[owner] : undefined;
      if (className) {
        const values = dedupeValues(enumVal as string[]);
        const prev = found.get(className);
        if (!prev) {
          found.set(className, { values, path: jsonPath });
        } else if (JSON.stringify(prev.values) !== JSON.stringify(values)) {
          throw new Error(
            `Enum "${className}" has divergent definitions in the spec:\n` +
              `  ${prev.path} (${prev.values.length} values)\n` +
              `  ${jsonPath} (${values.length} values)\n` +
              `Every occurrence of an enum is expected to be identical. An upstream ` +
              `restructure needs a human decision — inspect the spec.`,
          );
        }
      } else if (owner) {
        console.warn(
          `[gen-enums] Ignoring unmapped enum at "${jsonPath}" ` +
            `(owning property "${owner}", ${enumVal.length} values). ` +
            `Add it to PROPERTY_TO_CLASS if it should be generated.`,
        );
      }
    }

    for (const [key, value] of Object.entries(obj)) {
      walk(value, [...path, key]);
    }
  }

  walk(spec, []);

  const missing = Object.values(PROPERTY_TO_CLASS).filter((c) => !found.has(c));
  if (missing.length > 0) {
    throw new Error(
      `Spec is missing expected enum(s): ${missing.join(", ")}. ` +
        `A mapped request property was renamed or removed upstream — refusing to ` +
        `regenerate and silently drop an enum.`,
    );
  }

  const result: Record<string, string[]> = {};
  for (const className of Object.values(PROPERTY_TO_CLASS)) {
    const entry = found.get(className);
    // `entry` is always present here — the missing-enum check above guarantees it.
    if (entry) result[className] = entry.values;
  }
  return result;
}

/** Assemble the committed cache (`enum-source.json`) from a fetched spec. */
export function buildArtifact(spec: unknown): Artifact {
  const enums = extractEnums(spec);
  const version = (spec as { info?: { version?: unknown } })?.info?.version;
  return {
    _comment:
      "Enum value lists pulled from the Blitz OpenAPI spec and de-duplicated. " +
      "GENERATED by scripts/gen-enums.ts --fetch — do not hand-edit; run " +
      "`pnpm gen:enums:fetch` to refresh from the live spec. Each enum is inlined " +
      "and repeated across endpoints/content-types in the spec; identical " +
      "occurrences are collapsed and values are kept byte-for-byte (upstream " +
      "escaping preserved) so the SDK matches what the API accepts.",
    _source_url: SPEC_URL,
    spec_version: typeof version === "string" ? version : "unknown",
    enums,
  };
}

/**
 * Serialize the cache reproducing the committed format: 2-space-indented
 * top-level keys, 4-space-indented enum keys, each value list on one compact
 * line. Keeps the `enums` payload diff empty when only metadata changes.
 */
export function serializeArtifact(artifact: Artifact): string {
  const { enums, ...meta } = artifact;
  const metaLines = Object.entries(meta).map(
    ([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)}`,
  );
  const enumLines = Object.entries(enums).map(
    ([k, v]) => `    ${JSON.stringify(k)}: ${JSON.stringify(v)}`,
  );
  return `{\n${metaLines.join(",\n")},\n  "enums": {\n${enumLines.join(",\n")}\n  }\n}\n`;
}

export function render(): string {
  const data = JSON.parse(readFileSync(SOURCE, "utf8")) as { enums: Record<string, string[]> };
  const parts: string[] = [HEADER];

  for (const [className, values] of Object.entries(data.enums)) {
    const name = constName(className);
    const items = values.map((value) => `  ${JSON.stringify(value)},`).join("\n");
    parts.push(
      `\nexport const ${name} = [\n${items}\n] as const;\n` +
        `export type ${className} = (typeof ${name})[number];\n` +
        `export const ${className}Schema = z.enum(${name});\n`,
    );
  }

  return parts.join("");
}

/** Convert a PascalCase enum name to the SCREAMING_SNAKE const name. */
function constName(className: string): string {
  return className.replace(/([a-z0-9])([A-Z])/g, "$1_$2").toUpperCase();
}

function sleep(ms: number): Promise<void> {
  return new Promise((r) => setTimeout(r, ms));
}

/** Fetch + parse the OpenAPI spec, with a timeout and a small retry. */
async function fetchSpec(url: string): Promise<unknown> {
  let lastError: unknown;
  for (let attempt = 1; attempt <= FETCH_ATTEMPTS; attempt++) {
    try {
      const res = await fetch(url, {
        headers: { accept: "application/json" },
        signal: AbortSignal.timeout(FETCH_TIMEOUT_MS),
      });
      if (!res.ok) {
        throw new Error(`spec endpoint returned HTTP ${res.status} ${res.statusText}`);
      }
      const text = await res.text();
      try {
        return JSON.parse(text) as unknown;
      } catch (err) {
        throw new Error(`spec response was not valid JSON: ${(err as Error).message}`);
      }
    } catch (err) {
      lastError = err;
      if (attempt < FETCH_ATTEMPTS) {
        const backoff = 500 * attempt;
        console.warn(
          `[gen-enums] fetch attempt ${attempt} failed (${(err as Error).message}); ` +
            `retrying in ${backoff}ms…`,
        );
        await sleep(backoff);
      }
    }
  }
  throw new Error(
    `Could not fetch the OpenAPI spec from ${url} after ${FETCH_ATTEMPTS} attempts: ` +
      `${(lastError as Error)?.message ?? String(lastError)}. ` +
      `Run \`pnpm gen:enums:fetch\` again when online — CI does not need the network ` +
      `(\`pnpm gen:enums:check\` reads the committed cache).`,
  );
}

async function main(): Promise<number> {
  const fetchMode = process.argv.includes("--fetch");
  const check = process.argv.includes("--check");

  if (fetchMode) {
    const spec = await fetchSpec(SPEC_URL);
    const artifact = buildArtifact(spec);
    writeFileSync(SOURCE, serializeArtifact(artifact), "utf8");
    console.log(
      `Fetched spec from ${SPEC_URL} (version ${artifact.spec_version}); ` +
        `wrote ${relative(ROOT, SOURCE)} (${Object.keys(artifact.enums).length} enums).`,
    );
  }

  const rendered = render();

  if (check) {
    let current = "";
    try {
      current = readFileSync(TARGET, "utf8");
    } catch {
      current = "";
    }
    if (current !== rendered) {
      console.error("enums.ts is out of date. Run `pnpm gen:enums` and commit.");
      return 1;
    }
    console.log("enums.ts is up to date.");
    return 0;
  }

  writeFileSync(TARGET, rendered, "utf8");
  console.log(`Wrote ${relative(ROOT, TARGET)} (${rendered.split("\n").length} lines).`);
  return 0;
}

// Run only when invoked directly (not when imported by tests).
if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main().then(
    (code) => process.exit(code),
    (err: unknown) => {
      console.error(err instanceof Error ? err.message : String(err));
      process.exit(1);
    },
  );
}
