#!/usr/bin/env tsx
/**
 * Regenerate `src/types/enums.ts` from `openapi/enum-source.json`.
 *
 * The Blitz OpenAPI spec pins several request fields to large `enum` lists (most
 * notably `industry`, with hundreds of values). Hand-maintaining those would
 * drift from the API, so the value lists are vendored verbatim in
 * `openapi/enum-source.json` (byte-for-byte identical to the spec, copied from
 * the Python SDK) and this script turns them into:
 *
 *   - a `readonly` `as const` value array (e.g. `INDUSTRY`),
 *   - a string-literal union type (e.g. `Industry`), and
 *   - a Zod schema (e.g. `IndustrySchema = z.enum(INDUSTRY)`).
 *
 * Usage:
 *   tsx scripts/gen-enums.ts            # rewrite enums.ts
 *   tsx scripts/gen-enums.ts --check    # exit 1 if enums.ts is out of date
 *
 * CI runs `--check` so a stale generated file fails the build (drift guard).
 * Each value is emitted via `JSON.stringify` so the exact upstream escaping
 * (including the double-backslash apostrophe value) round-trips byte-for-byte.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SOURCE = join(ROOT, "openapi", "enum-source.json");
const TARGET = join(ROOT, "src", "types", "enums.ts");

const HEADER = `// This file is @generated by scripts/gen-enums.ts from openapi/enum-source.json.
// Do not edit by hand — run \`pnpm gen:enums\` to regenerate.
//
// Every value is the exact string the Blitz API accepts. Use the string literal
// directly (it autocompletes from the union type) or pass any raw string.
import * as z from "zod";
`;

interface EnumSource {
  enums: Record<string, string[]>;
}

/** Convert a PascalCase enum name to the SCREAMING_SNAKE const name. */
function constName(className: string): string {
  return className.replace(/([a-z0-9])([A-Z])/g, "$1_$2").toUpperCase();
}

export function render(): string {
  const data = JSON.parse(readFileSync(SOURCE, "utf8")) as EnumSource;
  const parts: string[] = [HEADER];

  for (const [className, values] of Object.entries(data.enums)) {
    const name = constName(className);
    const items = values.map((value) => `  ${JSON.stringify(value)},`).join("\n");
    parts.push(
      `\nexport const ${name} = [\n${items}\n] as const;\n` +
        `export type ${className} = (typeof ${name})[number];\n` +
        `export const ${className}Schema = z.enum(${name});\n`,
    );
  }

  return parts.join("");
}

function main(): number {
  const check = process.argv.includes("--check");
  const rendered = render();

  if (check) {
    let current = "";
    try {
      current = readFileSync(TARGET, "utf8");
    } catch {
      current = "";
    }
    if (current !== rendered) {
      console.error("enums.ts is out of date. Run `pnpm gen:enums` and commit.");
      return 1;
    }
    console.log("enums.ts is up to date.");
    return 0;
  }

  writeFileSync(TARGET, rendered, "utf8");
  console.log(`Wrote ${relative(ROOT, TARGET)} (${rendered.split("\n").length} lines).`);
  return 0;
}

process.exit(main());
